
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-03
owner: ucsb-cs156-s25
repo_name: team01-s25-03
pull_requests: [{"author":{"id":"U_kgDOCNntvg","is_bot":false,"login":"kwilliams812","name":"Kade Williams"},"headRefName":"Kade-EditOrgById","number":70,"title":"Add PUT (edit) endpoint for a single record in UCSBOrganization table","url":"https://github.com/ucsb-cs156-s25/team01-s25-03/pull/70"},{"author":{"id":"U_kgDOBvSp8w","is_bot":false,"login":"saahasburicha","name":"Saahas Buricha"},"headRefName":"pc-delete-for-helprequest-table","number":67,"title":"pc- added delete endpoint to the helprequest controller ","url":"https://github.com/ucsb-cs156-s25/team01-s25-03/pull/67"},{"author":{"id":"MDQ6VXNlcjY1OTQ0NzE3","is_bot":false,"login":"klai890","name":"Karena Lai"},"headRefName":"Karena-Articles-DELETE-Endpoint","number":52,"title":"Add DELETE endpoint for a specific record in Articles table","url":"https://github.com/ucsb-cs156-s25/team01-s25-03/pull/52"}]
