
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-03
owner: ucsb-cs156-s25
repo_name: team01-s25-03
pull_requests: [{"author":{"id":"U_kgDOCVHShQ","is_bot":false,"login":"xanxp","name":"Xin Ping Xandra Wong"},"headRefName":"xandra-UCSBDiningCommonsMenuItem-create-controller","number":55,"title":"xw - cleared unnecessary imports","url":"https://github.com/ucsb-cs156-s25/team01-s25-03/pull/55"},{"author":{"id":"U_kgDOB2-VXA","is_bot":false,"login":"daisyzhongg","name":""},"headRefName":"daisy-RecRequest","number":54,"title":"created database table for RecommendationRequest","url":"https://github.com/ucsb-cs156-s25/team01-s25-03/pull/54"},{"author":{"id":"MDQ6VXNlcjY1OTQ0NzE3","is_bot":false,"login":"klai890","name":"Karena Lai"},"headRefName":"Karena-Articles-DELETE-Endpoint","number":52,"title":"Add DELETE endpoint for a specific record in Articles table","url":"https://github.com/ucsb-cs156-s25/team01-s25-03/pull/52"},{"author":{"id":"MDQ6VXNlcjY1OTQ0NzE3","is_bot":false,"login":"klai890","name":"Karena Lai"},"headRefName":"Karena-Articles-PUT-Endpoint","number":50,"title":"Add PUT (edit) endpoint for a single record in Articles table","url":"https://github.com/ucsb-cs156-s25/team01-s25-03/pull/50"},{"author":{"id":"MDQ6VXNlcjY1OTQ0NzE3","is_bot":false,"login":"klai890","name":"Karena Lai"},"headRefName":"Karena-Articles-GET-Endpoint","number":48,"title":"Add GET (show) endpoint for a single record in Articles table","url":"https://github.com/ucsb-cs156-s25/team01-s25-03/pull/48"}]
